openapi: 3.0.0
info:
  title: Saint Egidio Admin API
  description: API для управления временными слотами, локациями и услугами в административной панели Saint Egidio
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Development server
security:
  - BearerAuth: []
paths:
  /locations:
    get:
      tags:
        - locations
      summary: Получение списка локаций
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
                maxItems: 100
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - locations
      summary: Создание новой локации
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLocationRequest"
        required: true
      responses:
        "201":
          description: Локация успешно создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
              example:
                id: 3
                name: Новый храм
                address: ул. Новая, 67
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /locations/{id}:
    put:
      tags:
        - locations
      summary: Обновление локации по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLocationRequest"
        required: true
      responses:
        "200":
          description: Локация успешно обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - locations
      summary: Удаление локации по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Локация успешно удалена
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /services:
    get:
      tags:
        - services
      summary: Получение списка услуг
      parameters:
        - name: registration_available
          in: query
          style: form
          explode: true
          schema:
            type: boolean
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ServiceType"
                maxItems: 100
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /services/{id}:
    get:
      tags:
        - services
      summary: Получение информации об услуге по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceType"
              example:
                id: 1
                name: Исповедь
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - services
      summary: Обновление информации об услуге по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateServiceRegistrationRequest"
        required: true
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceType"
              example:
                id: 1
                name: Исповедь
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /timeSlots:
    get:
      tags:
        - timeSlots
      summary: Получение списка временных слотов
      description: Возвращает список временных слотов с возможностью фильтрации
      parameters:
        - name: status
          in: query
          style: form
          explode: true
          schema:
            type: string
            enum:
              - active
              - archived
        - name: startDate
          in: query
          style: form
          explode: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          style: form
          explode: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TimeSlot"
                maxItems: 100
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - timeSlots
      summary: Создание нового временного слота
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTimeSlotRequest"
        required: true
      responses:
        "201":
          description: Временной слот успешно создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSlot"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /timeSlots/{id}:
    get:
      tags:
        - timeSlots
      summary: Получение временного слота по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Временной слот
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSlot"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - timeSlots
      summary: Обновление временного слота
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TimeSlot"
        required: true
      responses:
        "200":
          description: Временной слот успешно обновлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSlot"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - timeSlots
      summary: Удаление временного слота
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Временной слот успешно удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /timeSlots/{id}/activate:
    patch:
      tags:
        - timeSlots
      summary: Активация временного слота
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
          example: 1
      responses:
        "200":
          description: Временной слот успешно активирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSlot"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /timeSlots/{id}/archive:
    patch:
      tags:
        - timeSlots
      summary: Архивация временного слота
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Временной слот успешно архивирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSlot"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /events:
    get:
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: participant_id
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - upcoming
              - past
        - name: location
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: service_id
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: from_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: to_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
      tags:
        - events
      summary: Получение списка событий
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Event"
                  total:
                    type: integer
                    format: int64
                  page:
                    type: integer
                    format: int32
                  per_page:
                    type: integer
                    format: int32
                  total_pages:
                    type: integer
                    format: int32
                required:
                  - items
                  - total
                  - page
                  - per_page
                  - total_pages
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /events/{id}:
    get:
      tags:
        - events
      summary: Получение события по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - events
      summary: Обновление события по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEventRequest"
        required: true
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - events
      summary: Удаление события по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "400":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
      required:
        - id
        - name
      example:
        id: 1
        name: Главный храм
        address: ул. Примерная, 123
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string
      required:
        - code
        - message
      example:
        code: VALIDATION_ERROR
        message: Ошибка валидации
        details: Поле 'name' обязательно для заполнения
    CreateLocationRequest:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
      required:
        - name
        - address
      example:
        name: Новый храм
        address: ул. Новая, 67
    UpdateLocationRequest:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
      required:
        - name
        - address
      example:
        name: Новый храм
        address: ул. Новая, 67
    ServiceType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        min_period_days:
          type: integer
          format: int32
        registration_available:
          type: boolean
      required:
        - id
        - name
        - min_period_days
        - registration_available
      example:
        id: 1
        name: Исповедь
        min_period_days: 1
        registration_available: true
    UpdateServiceRegistrationRequest:
      type: object
      properties:
        min_period_days:
          type: integer
          format: int32
        registration_available:
          type: boolean
      required:
        - min_period_days
        - registration_available
      example:
        min_period_days: 1
        registration_available: true
    TimeSlotService:
      type: object
      properties:
        id:
          type: integer
          format: int64
        serviceTypeId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        bookingWindow:
          type: integer
          format: int32
        time:
          type: string
          format: date-time
      required:
        - serviceTypeId
        - capacity
        - bookingWindow
        - time
      example:
        serviceTypeId: 1
        capacity: 20
        bookingWindow: 30
        time: "2024-03-20T09:00:00Z"
    Recurrence:
      type: object
      properties:
        frequency:
          type: string
          enum:
            - daily
            - weekly
            - monthly
        interval:
          type: integer
          format: int32
          minimum: 1
        endType:
          type: string
          enum:
            - never
            - date
        endValue:
          type: string
          format: date-time
          nullable: true
      required:
        - frequency
        - interval
        - endType
      example:
        frequency: weekly
        interval: 1
        endType: date
        endValue: "2024-04-20T19:00:00Z"
    TimeSlot:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        type:
          type: string
          enum:
            - single
            - recurring
        locationId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - active
            - archived
        services:
          type: array
          items:
            $ref: "#/components/schemas/TimeSlotService"
        recurrence:
          $ref: "#/components/schemas/Recurrence"
      required:
        - id
        - title
        - type
        - locationId
        - capacity
        - startDate
        - endDate
        - status
        - services
      example:
        id: 1
        title: Утренняя служба
        type: single
        locationId: 1
        capacity: 50
        startDate: "2024-03-20T09:00:00Z"
        endDate: "2024-03-20T10:00:00Z"
        status: active
        services:
          - timeSlotId: 1
            serviceTypeId: 1
            capacity: 20
            bookingWindow: 30
            time: "2024-03-20T09:00:00Z"
          - timeSlotId: 1
            serviceTypeId: 2
            capacity: 30
            bookingWindow: 30
            time: "2024-03-20T09:30:00Z"
    CreateTimeSlotRequest:
      type: object
      properties:
        title:
          type: string
        type:
          type: string
          enum:
            - single
            - recurring
        locationId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
          x-validate:
            - rule: startDate must be in the future
              condition: startDate > now
            - rule: startDate must be before endDate
              condition: startDate < endDate
        endDate:
          type: string
          format: date-time
          x-validate:
            - rule: endDate must be after startDate
              condition: endDate > startDate
        services:
          type: array
          items:
            $ref: "#/components/schemas/TimeSlotService"
        recurrence:
          $ref: "#/components/schemas/Recurrence"
      required:
        - title
        - type
        - locationId
        - capacity
        - startDate
        - endDate
        - services
      examples:
        title: Тест повторение
        type: recurring
        locationId: 1
        capacity: 100
        startDate: "2025-03-20T18:00:00Z"
        endDate: "2025-03-20T19:00:00Z"
        services:
          - serviceTypeId: 1
            capacity: 40
            bookingWindow: 30
            time: "2025-03-20T18:00:00Z"
          - serviceTypeId: 2
            capacity: 60
            bookingWindow: 30
            time: "2025-03-20T18:30:00Z"
        recurrence:
          frequency: weekly
          interval: 1
          endType: date
          endValue: "2025-04-20T19:00:00Z"
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        timeSlotServiceId:
          type: integer
          format: int64
        serviceTypeId:
          type: integer
          format: int64
        capacity:
          type: integer
          format: int32
        datetime:
          type: string
          format: date-time
      required:
        - timeSlotServiceId
        - capacity
        - datetime
      example:
        id: 1
        timeSlotServiceId: 1
        capacity: 20
        datetime: "2024-03-20T09:00:00Z"
    UpdateEventRequest:
      type: object
      properties:
        capacity:
          type: integer
          format: int32
        datetime:
          type: string
          format: date-time
      required:
        - capacity
        - datetime
      example:
        capacity: 20
        datetime: "2024-03-20T09:00:00Z"
